version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "chachou8106-blip"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "bot"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "chachou8106-blip"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "bot"
